version: "3"

services:
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                     C O D E I G N I T E R  v4.1.8                        #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
    brighty:
        image: shinsenter/codeigniter4:php8.1-tidy
        container_name: 'brighty'
        ports:
          - 80:80
          - 443:443
        links:
          - brighty_mysql
        volumes:
          - ./www/brighty/:/var/www/html

#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                               M Y S Q L                                  #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#               
    brighty_mysql:
        image: mariadb:10.5.5
        container_name: 'brighty_mysql'
        ports:
          - 3306:3306
        volumes:
          - ./mysql:/var/lib/mysql
          - ./logs/mysql:/var/log/mysql
        environment:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: codeigniter4
          MYSQL_USER: codeigniter4
          MYSQL_PASSWORD: codeigniter4

#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                         P H P M Y A D M I N                              #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#             
    codeigniter4_phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.0.2
        container_name: 'codeigniter4_phpmyadmin'
        links:
          - brighty_mysql
        environment:
          PMA_HOST: brighty_mysql
          PMA_PORT: 3306
        ports:
          - 81:80
        volumes:
          - ./sessions:/sessions