
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                            B R I G H T Y                                 #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
version: "3"

services:
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                           W O R D P R E S S                              #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
    brighty:
        # image: docker.io/bitnami/laravel:9 
        # ports:
        #   - 8000:8000
        #   - 443:443
        # links:
        #   - brighty_mysql
        # volumes:
        #   - ./:/app    
  
      image: docker.io/wordpress
      container_name: 'brighty'
      ports:
        - '8080:80'
        - 443:443
      environment:
        - WORDPRESS_DB_HOST=brighty_mysql
        - WORDPRESS_DB_PORT=3306
        - WORDPRESS_DB_NAME=brighty
        - WORDPRESS_DB_USER=root
        - WORDPRESS_DB_PASSWORD=BrightyP
        - WORDPRESS_TABLE_PREFIX=wp
        - WORDPRESS_DEBUG=1
      volumes:
        - './brighty:/var/www/html'
        - './themes:/var/www/html/wp-content/themes'
        - './plugins:/var/www/html/wp-content/plugins'
      depends_on:
        - brighty_mysql

#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                               M Y S Q L                                  #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#               
    brighty_mysql:
        image: mariadb:10.5.5
        container_name: 'brighty_mysql'
        ports:
          - 3306:3306
        volumes:
          - ./database/mysql:/var/lib/mysql
          - ./database/logs/mysql:/var/log/mysql
        environment:
          MYSQL_DATABASE: brighty
          MYSQL_USER: brighty_user
          MYSQL_PASSWORD: BrightyP
          MYSQL_ROOT_PASSWORD: BrightyP

#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                         P H P M Y A D M I N                              #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#             
    brighty_phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.0.2
        container_name: 'laravel_phpmyadmin'
        links:
          - brighty_mysql
        environment:
          PMA_HOST: brighty_mysql
          PMA_PORT: 3306
        ports:
          - 81:80
        volumes:
          - ./database/sessions:/sessions